[build]
    functions = "functions"  # Specifies the directory where your functions are located

[functions]
    directory = "functions"  # Specifies the directory where your functions are located

# You can add additional settings here as needed
